apiVersion: v1
kind: Namespace
metadata:
  name: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapi-deployment
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldapi
  template:
    metadata:
      labels:
        app: helloworldapi
    spec:
      containers:
      - name: helloworldapi
        image: srpadalaacr.azurecr.io/helloworldapi:latest
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: helloworldapi-service
  namespace: hello-world
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '100'  
spec:
  type: LoadBalancer
  selector:
    app: helloworldapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080